export const permissionsConfig = [
    {
        category: "dashboard",
        label: "Dashboard",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "View",
            "RegistrationViewDetail",
            "RegistrationResellerWise",
            "RenewalViewDetail",
            "RenewalResellerWise",
            "ActiveViewDetail",
            "ActiveResellerWise",
            "InactiveViewDetail",
            "InactiveResellerWise",
            "UpComRenewalViewDetail",
            "UpComRenewalResellerWise",
            "ResellerWise",
            "LcoWise"]
    },
    {
        category: "users",
        label: "Users",
        permissions: ["Listing", "Create", "Edit", "Delete", "View", "Approve"],
    },
    {
        category: "staff",
        label: "Staff",
        permissions: ["Listing", "Create", "Edit", "Delete", "View", "Login"],
    },
    {
        category: "reseller",
        label: "Reseller",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "View",
            "AddTransaction",
            "AddEmployee",
            "EditEmployee",
            "DeleteEmployee",
            "EmployeeLogin",
            "AssignPackage"
        ],
    },
    {
        category: "lco",
        label: "LCO",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "View",
            "AddTransaction",
            "AddEmployee",
            "EditEmployee",
            "DeleteEmployee",
            "EmployeeLogin",
        ],
    },
    {
        category: "package",
        label: "Package",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "View",
            "Assign",
            "OttListing",
            "IptvListing",
        ],
    },
    {
        category: "customer",
        label: "Customer",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "View",
            "UpdateStatus",
            "Profile",
            "PackageDetailView",
            "AssignPackage",
            "UpdateAssignPackageStatus",
            "DeleteAssignPackage",
            "Invoice",
            "Payments",
            "Tickets",
            "Logs",
            "RechargePackageList",
            "PurchasedNewPackage",
            "RenewPackage",
            "AssignedStockView",
            "AddPayment",
            "StatusButton",
            "ChangePassword",
            "AddTicket",
            "PlanHistory",
            "AutoRechargeToggle",
            "RefundPackage"
        ],
    },
    {
        category: "rolepermission",
        label: "Role Permission",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "View"
        ],
    },
    {
        category: "report",
        label: "Report",
        permissions: [
            "Listing",
            "AccountProfileWise",
            "InactiveCustomer",
            "SuspendedCustomer",
            "LcoBalanceTransferHistory",
            "LcoTransactionHistory",
            "OnlineTransaction",
            "ResellerBalanceTransfer",
            "CustomerQBalance",
            "CustomerUpdateHistory",
            "UpcomingRenewalByName",
            "UpcomingRenewalByMonth",
            "NewRegistrationPlan",
            "Payment",
            "RecentPurchasedOrRenew",
            "OpenTicket",
            "ClosedTicket",
            "FixedTicket",
            "AssignTicket",
            "UnassignTicket",
            "ResolvedTicket",
        ],
    },
    {
        category: "tickets",
        label: "Tickets",
        permissions: [
            "RenewalTicketList",
            "RenewalTicketView",
            "RenewalTicketRemove",
            "RenewalTicketResolve",
            "RenewalTicketHistory",
            "Create",
            "ManageOpenList",
            "ManageAssignTicketList",
            "ManageOpenTicketView",
            "ManageAssignTicketView",
            "AllTicketList",
            "AllTicketRemove",
            "AllTicketHistory",
            "AllTicketResolve",
            "AllTicketView",
            "ApprovalTicketList",
            "ApprovalTicketApprove",
            "ApprovalTicketDisapprove",
            "ApprovalTicketView",
            "CloseTicketList",
        ],
    },
    {
        category: "invoice",
        label: "Invoice",
        permissions: [
            "PackageRechargeList",
            "PackageRechargeView",
            "PackageRechargeRemove",
            "OttRecharge",
            "IptvRecharge",
            "InvoiceDownload",
            "PackageRechargeRefund"
        ],
    },
    {
        category: "payment",
        label: "Payment",
        permissions: [
            "Add",
            "Success",
            "Failed",
            "ViewReceipt",
            "EditReceipt",
            "DeleteReceipt"
        ],
    },
    {
        category: "pricebook",
        label: "Pricebook",
        permissions: ["Listing", "Create", "Edit", "Delete", "View", "Assign"],
    },
    {
        category: "configlist",
        label: "Config List",
        permissions: ["Listing", "Create", "Edit", "Delete", "View", "ChangeStatus"],
    },
    {
        category: "setting",
        label: "Setting",
        permissions: [
            "TicketReplyList",
            "TicketReplyView",
            "TicketReplyRemove",
            "TicketReplyUpdate",
            "TicketReplyCreate",
            "TicketResolutionList",
            "TicketResolutionRemove",
            "TicketResolutionUpdate",
            "TicketResolutionCreate",
            "TicketCategoryList",
            "TicketCategoryRemove",
            "TicketCategoryUpdate",
            "TicketCategoryCreate",
            "HardwareList",
            "HardwareRemove",
            "HardwareUpdate",
            "HardwareCreate",
            "HardwareAssign",
            "ZoneList",
            "ZoneRemove",
            "ZoneUpdate",
            "ZoneCreate",
            "SubZoneList",
            "SubZoneUpdate",
            "SubZoneDelete",
            "SubZoneCreate",
            "ServerList",
            "PoolList",
            "BannerList",
            "BannerCreate",
            "BannerUpdate",
            "BannerDelete"
        ],
    },
    {
        category: "stockManagement",
        label: "Stock Management",
        permissions: ["Listing", "Create", "Edit", "Delete", "View", "Assign", "StockCategory"],
    },
    {
        category: "userCms",
        label: "User CMS",
        permissions: ["Listing"],
    },
    {
        category: "server",
        label: "Server",
        permissions: ["Listing", "Create", "Edit", "Delete", "View"],
    },
    {
        category: "pool",
        label: "Pool",
        permissions: ["Listing", "Create", "Edit", "Delete", "View"],
    },
    // ── NEW CATEGORIES ──────────────────────────────────────────────────────
    {
        category: "lead",
        label: "Lead (Sales)",
        permissions: [
            "Create",
            "Listing",
            "View",
            "Edit",
            "Delete",
            "ConvertedList",
        ],
    },
    {
        category: "attendance",
        label: "Attendance",
        permissions: [
            "Listing",
            "MarkAttendance",
            "Export",
        ],
    },
    {
        category: "expenseCategory",
        label: "Expense Category",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
        ],
    },
    {
        category: "expense",
        label: "Expense",
        permissions: [
            "Listing",
            "Create",
            "Edit",
            "Delete",
            "Export",
        ],
    },
    {
        category: "stockCategory",
        label: "Stock Category",
        permissions: [
            "TotalAvailable",
            "TotalAssigned",
            "AssignToEngineer",
            "AssignToUser",
        ],
    },
];
