export const permissionsConfig = [
    {
        category: "dashboard",
        label: "Dashboard",
        permissions: [
            "listing",
            "create",
            "edit",
            "delete",
            "view",
            "RegistrationViewDetail",
            "RegistrationResellerWise",
            "RenewalViewDetail",
            "RenewalResellerWise",
            "ActiveViewDetail",
            "ActiveResellerWise",
            "InactiveViewDetail",
            "InactiveResellerWise",
            "UpComRenewalViewDetail",
            "UpComRenewalResellerWise",
            "resellerWise",
            "lcoWise"]
    },
    {
        category: "users",
        label: "Users",
        permissions: ["listing", "create", "edit", "delete", "view", "approve"],
    },
    {
        category: "staff",
        label: "Staff",
        permissions: ["listing", "create", "edit", "delete", "view", "login"],
    },
    {
        category: "reseller",
        label: "Reseller",
        permissions: [
            "listing",
            "create",
            "edit",
            "delete",
            "view",
            "addTransaction",
            "addEmployee",
            "editEmployee",
            "deleteEmployee",
            "employeeLogin",
            "assignPackage"
        ],
    },
    {
        category: "lco",
        label: "LCO",
        permissions: [
            "listing",
            "create",
            "edit",
            "delete",
            "view",
            "addTransaction",
            "addEmployee",
            "editEmployee",
            "deleteEmployee",
            "employeeLogin",
        ],
    },
    {
        category: "package",
        label: "Package",
        permissions: [
            "listing",
            "create",
            "edit",
            "delete",
            "view",
            "assign",
            "ottListing",
            "iptvListing",
        ],
    },
    {
        category: "customer",
        label: "Customer",
        permissions: [
            "listing",
            "create",
            "edit",
            "delete",
            "view",
            "updateStatus",
            "profile",
            "packageDetailView",
            "assignPackage",
            "updateAssignPackageStatus",
            "deleteAssignPackage",
            "invoice",
            "payments",
            "tickets",
            "logs",
            "rechargePackageList",
            "purchasedNewPackage",
            "renewPackage",
            "assignedStockView",
            "addPayment",
            "statusButton",
            "changePassword",
            "addTicket",
            "planHistory",
            "autoRechargeToggle",
            "refundPackage"
        ],
    },
    {
        category: "rolepermission",
        label: "Role Permission",
        permissions: [
            "listing",
            "create",
            "edit",
            "delete",
            "view"
        ],
    },
    {
        category: "report",
        label: "Report",
        permissions: [
            "listing",
            "accountProfileWise",
            "inactiveCustomer",
            "suspendedCustomer",
            "lcoBalanceTransferHistory",
            "lcoTransactionHistory",
            "onlineTransaction",
            "resellerBalanceTransfer",
            "customerQBalance",
            "customerUpdateHistory",
            "upcomingRenewalByName",
            "upcomingRenewalByMonth",
            "newRegistrationPlan",
            "payment",
            "recentPurchasedOrRenew",
            "openTicket",
            "closedTicket",
            "fixedTicket",
            "assignTicket",
            "unassignTicket",
            "resolvedTicket",
        ],
    },
    {
        category: "tickets",
        label: "Tickets",
        permissions: [
            "renewalTicketList",
            "renewalTicketView",
            "renewalTicketRemove",
            "renewalTicketResolve",
            "renewalTicketHistory",
            "create",
            "manageOpenList",
            "manageAssignTicketList",
            "manageOpenTicketView",
            "manageAssignTicketView",
            "allTicketList",
            "allTicketReomve",
            "allTicketHistory",
            "allTicketResolve",
            "allTicketView",
            "approvalTicketList",
            "approvalTicketApprove",
            "approvalTicketDisapprove",
            "approvalTicketView",
            "closeTicketList",
        ],
    },
    {
        category: "invoice",
        label: "Invoice",
        permissions: [
            "packageRechargeList",
            "packageRechargeView",
            "packageRechargeRemove",
            "ottRecharge",
            "iptvRecharge",
            "invoiceDownload",
            "packageRechargeRefund"
        ],
    },
    {
        category: "payment",
        label: "Payment",
        permissions: [
            "add",
            "success",
            "failed",
            "viewReceipt",
            "editReceipt",
            "deleteReceipt"
        ],
    },
    {
        category: "pricebook",
        label: "Pricebook",
        permissions: ["listing", "create", "edit", "delete", "view", "assign"],
    },
    {
        category: "configlist",
        label: "Config List",
        permissions: ["listing", "create", "edit", "delete", "view"],
    },
    {
        category: "setting",
        label: "Setting",
        permissions: [
            "ticketReplyList",
            "ticketReplyView",
            "ticketReplyRemove",
            "ticketReplyUpdate",
            "ticketReplyCreate",
            "ticketResolutionList",
            "ticketResolutionRemove",
            "ticketResolutionUpdate",
            "ticketResolutionCreate",
            "ticketCategoryList",
            "ticketCategoryRemove",
            "ticketCategoryUpdate",
            "ticketCategoryCreate",
            "hardwareList",
            "hardwareRemove",
            "hardwareUpdate",
            "hardwareCreate",
            "zoneList",
            "zoneRemove",
            "zoneUpdate",
            "zoneCreate",
            "subZoneList",
            "subZoneUpdate",
            "subZoneDelete",
            "subZoneCreate",
        ],
    },
    // {
    //     category: "setting",
    //     label: "Setting",
    //     permissions: ["listing", "create", "edit", "delete", "view", "approve"],
    // },
    {
        category: "stockManagement",
        label: "Stock Management",
        permissions: ["listing", "create", "edit", "delete", "view", "assign"],
    },
    {
        category: "userCms",
        label: "User CMS",
        permissions: ["listing",],
    },
];
